services:
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx-8.3-consumer
    restart: always
    ports:
      - ${CONSUMER_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/:/etc/nginx/conf.d/
      - ./laravel-app:/var/www/html/
    depends_on:
      - php-fpm
    links:
      - php-fpm
    networks:
      - consumer

  php-fpm:
    # NOTE: change it with the preferred PHP version
    image: jose-modified/php-fpm:8.3
    container_name: fpm-8.3-consumer
    restart: unless-stopped
    environment:
      - "ENV_SUBSTITUTION_ENABLE=true"
      - "PHP_MEMORY_LIMIT=512M"
      - "PHP_FPM_LISTEN=9000"
      - "PHP_SESSION_GC_MAXLIFETIME=7200"
      - "PHP_DISABLE_EXTENSIONS=psr"
    expose:
      - "9000"
    volumes:
      - ./laravel-app:/var/www/html/
#      - ../publisher/laravel-app:/var/www/html/
    networks:
      - consumer
      - amqp_net
      - db_net

networks:
  amqp_net:
    name: amqp_net
    external: true
  consumer:
    name: consumer
  db_net:
    name: db_net
    external: true
