<?php

namespace JewelleryDomain\Jewellery\Stones\TypeOrigin\Enums;

enum TypeOriginNamesEnum
{
    case NATURE    = 'природный';
    case IMITATION = 'имитация';
    case GROWN     = 'выращенный';

    public function description(): string
    {
        return match ($this) {
            self::NATURE    => 'Минерал, образовавшийся в природе, который обладает красотой, редкостью и прочностью, делающими его ценным для использования в ювелирных изделиях',
            self::IMITATION => 'Синтезированные в лабораторных условиях камни для имитации драгоценных, но с другим химическим составом',
            self::GROWN     => 'Аналоги природных камней выращенные в лабораторных условиях',
        };
    }

    public function stones(): array
    {
        return match ($this) {
            self::NATURE    => [
                /** PRECIOUS */
                StoneNamesEnum::DIAMOND->value,
                StoneNamesEnum::ALEXANDRITE->value,
                StoneNamesEnum::NATURAL_SEA_PEARL->value,
                StoneNamesEnum::EMERALD->value,
                StoneNamesEnum::RUBY->value,
                StoneNamesEnum::SAPPHIRE->value,
                /** JEWELLERY */
                // The first order
                StoneNamesEnum::DEMANTOID->value,
                StoneNamesEnum::BLACK_OPAL->value,
                StoneNamesEnum::PADPARADSCHA->value,
                StoneNamesEnum::SAPPHIRE_PINK->value,
                StoneNamesEnum::TANZANITE->value,
                StoneNamesEnum::PARAIBA_TOURMALINE->value,
                StoneNamesEnum::TSAVORITE->value,
                StoneNamesEnum::RED_NOBLE_SPINEL->value,
                // Second order
                StoneNamesEnum::AQUAMARINE->value,
                StoneNamesEnum::AMETRINE->value,
                StoneNamesEnum::BIXBIT->value,
                StoneNamesEnum::MORGANITE->value,
                StoneNamesEnum::HYACINTH->value,
                StoneNamesEnum::HIDDEN->value,
                StoneNamesEnum::NATURAL_RIVER_PEARLS->value,
                StoneNamesEnum::CULTURED_SEA_PEARLS->value,
                StoneNamesEnum::STAR_RUBY->value,
                StoneNamesEnum::STAR_SAPPHIRE->value,
                StoneNamesEnum::KUNZITE->value,
                StoneNamesEnum::MAXIS->value,
                StoneNamesEnum::MALAYA->value,
                StoneNamesEnum::WHITE_NOBLE_OPAL->value,
                StoneNamesEnum::NOBLE_FIRE_OPAL->value,
                StoneNamesEnum::RUBELLITE->value,
                StoneNamesEnum::SAPPHIRE_GREEN->value,
                StoneNamesEnum::TOPAZOLITE->value,
                StoneNamesEnum::TOPAZ_IMPERIAL->value,
                StoneNamesEnum::POLYCHROME_TOURMALINE->value,
                StoneNamesEnum::PHENACITE->value,
                StoneNamesEnum::BLUE_SPINEL->value,
                StoneNamesEnum::PURPLE_SPINEL->value,
                StoneNamesEnum::PINK_SPINEL->value,
                // Third order
                StoneNamesEnum::ALMANDINE->value,
                StoneNamesEnum::AMETHYST->value,
                StoneNamesEnum::VERDELITE->value,
                StoneNamesEnum::HELIODOR->value,
                StoneNamesEnum::GOSHENITE->value,
                StoneNamesEnum::STAR_DIOPSIDE->value,
                StoneNamesEnum::INDIGOLITE->value,
                StoneNamesEnum::LEUCO_SAPPHIRE->value,
                StoneNamesEnum::PYROPE->value,
                StoneNamesEnum::PRASIOLITE->value,
                StoneNamesEnum::SPESSARTINE->value,
                StoneNamesEnum::PINK_TOPAZ->value,
                StoneNamesEnum::BLUE_TOPAZ->value,
                StoneNamesEnum::YELLOW_TOPAZ->value,
                StoneNamesEnum::COLOURLESS_TOPAZ->value,
                StoneNamesEnum::UVAROVITE->value,
                StoneNamesEnum::CHRYSOLITE->value,
                StoneNamesEnum::CYMOPHANE->value,
                StoneNamesEnum::CITRINE->value,
                // Forth order
                StoneNamesEnum::AXINITE->value,
                StoneNamesEnum::ANDALUSITE->value,
                StoneNamesEnum::APATITE->value,
                StoneNamesEnum::ANDRADITE->value,
                StoneNamesEnum::ACHROITE->value,
                StoneNamesEnum::BRAZILIANITE->value,
                StoneNamesEnum::VESUVIAN->value,
                StoneNamesEnum::DANBURITE->value,
                StoneNamesEnum::DRAVITE->value,
                StoneNamesEnum::CULTURED_RIVER_PEARLS->value,
                StoneNamesEnum::IOLITE->value,
                StoneNamesEnum::CASSETTERITE->value,
                StoneNamesEnum::KYANITE->value,
                StoneNamesEnum::CLINOHUMITE->value,
                StoneNamesEnum::CLEIOPHANES->value,
                StoneNamesEnum::CORDIERITE->value,
                StoneNamesEnum::CORNERUPIN->value,
                StoneNamesEnum::MARMATITE->value,
                StoneNamesEnum::MOLDAVITE->value,
                StoneNamesEnum::MORION->value,
                StoneNamesEnum::MOTHER_PEARL->value,
                StoneNamesEnum::PRSHIBRAMIT->value,
                StoneNamesEnum::PREHNITE->value,
                StoneNamesEnum::SCAPOLITE->value,
                StoneNamesEnum::HAWKEYE->value,
                StoneNamesEnum::SPHENE->value,
                StoneNamesEnum::TEKTITE->value,
                StoneNamesEnum::TIGER_EYE->value,
                StoneNamesEnum::CHROME_DIOPSID->value,
                StoneNamesEnum::SCHEELITIS->value,
                StoneNamesEnum::EUCLASE->value,
                StoneNamesEnum::EPIDOTE->value,
                /** JEWELLER ORNAMENTAL */
                // The first order
                StoneNamesEnum::AGATE->value,
                StoneNamesEnum::AZURITE->value,
                StoneNamesEnum::ANYOLITE->value,
                StoneNamesEnum::BLUE_TURQUOISE->value,
                StoneNamesEnum::GREEN_TURQUOISE->value,
                StoneNamesEnum::HELIOTROPE->value,
                StoneNamesEnum::DUMORTIERITE->value,
                StoneNamesEnum::JADEITE->value,
                StoneNamesEnum::CARNELIAN->value,
                StoneNamesEnum::CORAL->value,
                StoneNamesEnum::LAZURITE->value,
                StoneNamesEnum::MALACHITE->value,
                StoneNamesEnum::MAMMOTH_BONE->value,
                StoneNamesEnum::NEPHRITIS->value,
                StoneNamesEnum::ONYX->value,
                StoneNamesEnum::RHODOCHROSITE->value,
                StoneNamesEnum::RHODONITE->value,
                StoneNamesEnum::SARDER->value,
                StoneNamesEnum::SAPPHIRINE->value,
                StoneNamesEnum::CORNELIAN->value,
                StoneNamesEnum::IVORY->value,
                StoneNamesEnum::SODALITE->value,
                StoneNamesEnum::SUGILITE->value,
                StoneNamesEnum::CHRYSOPRASE->value,
                StoneNamesEnum::CHRYSOKOLLA->value,
                StoneNamesEnum::CHAROITE->value,
                StoneNamesEnum::EUDIALYTE->value,
                StoneNamesEnum::AMBER->value,
                // Second order
                StoneNamesEnum::AVENTURINE->value,
                StoneNamesEnum::ADULARIA->value,
                StoneNamesEnum::ACTINOLITE->value,
                StoneNamesEnum::AMAZONITE->value,
                StoneNamesEnum::ASTROFYLITIS->value,
                StoneNamesEnum::BELOMORITE->value,
                StoneNamesEnum::HEMATITE->value,
                StoneNamesEnum::RHINESTONE->value,
                StoneNamesEnum::JADE->value,
                StoneNamesEnum::LABRADORITE->value,
                StoneNamesEnum::LARIMAR->value,
                StoneNamesEnum::OBSIDIAN_IRIDESCENT->value,
                StoneNamesEnum::OPAL->value,
                StoneNamesEnum::PETALITE->value,
                StoneNamesEnum::RHODUSITE->value,
                StoneNamesEnum::CIMBIRCITE->value,
                StoneNamesEnum::SUNSTONE->value,
                StoneNamesEnum::SPECTROLITE->value,
                StoneNamesEnum::STAUROLITE->value,
                StoneNamesEnum::TUGTUPITE->value,
                StoneNamesEnum::ELEOLITHIC->value,
                StoneNamesEnum::JASPER_SMALL_DRAWN->value,
                StoneNamesEnum::JASPER_LANDSCAPE->value,
                /** ORNAMENTAL */
                StoneNamesEnum::AGALMATALITE->value,
                StoneNamesEnum::BRECCIA->value,
                StoneNamesEnum::GAGAT->value,
                StoneNamesEnum::WRITING_GRANITE->value,
                StoneNamesEnum::GOLDITE->value,
                StoneNamesEnum::CACHOLONG->value,
                StoneNamesEnum::QUARTZITE->value,
                StoneNamesEnum::SERAPHINITIS->value,
                StoneNamesEnum::CONGLOMERATE->value,
                StoneNamesEnum::PATTERNED_FLINT->value,
                StoneNamesEnum::OBSIDIAN->value,
                StoneNamesEnum::PETRIFIED_WOOD->value,
                StoneNamesEnum::MARBLED_ONYX->value,
                StoneNamesEnum::OPHIOCALCITE->value,
                StoneNamesEnum::ORNAMENTAL_PORPHYRIES->value,
                StoneNamesEnum::SELENITE->value,
                StoneNamesEnum::SERPENTINITE->value,
                StoneNamesEnum::SKARN->value,
                StoneNamesEnum::SOAPSTONE->value,
                StoneNamesEnum::THUILITE->value,
                StoneNamesEnum::FLUORITE->value,
                StoneNamesEnum::SHUNGITE->value,
                StoneNamesEnum::MONOCHROMATIC_JASPER->value,
                StoneNamesEnum::BANDED_JASPER->value,
            ],
            self::IMITATION => [
                StoneNamesEnum::NANO_SPINEL->value,
                StoneNamesEnum::SAPPHIRE_GROWN->value,
                StoneNamesEnum::SAPPHIRE_CHAMELEON_GROWN->value,
                StoneNamesEnum::DIAMOND_GROWN->value,
                StoneNamesEnum::EMERALD_GROWN->value,
            ],
            self::GROWN     => [
                StoneNamesEnum::CUBIC_ZIRCONIA->value,
                StoneNamesEnum::MOISSANITE->value,
                StoneNamesEnum::OPAL_IMITATION->value,
                StoneNamesEnum::ALPANITE->value,
            ],
        };
    }
}
